version: '3.8'

services:
  backend:
    build: ./backend
    container_name: duotax-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: duotax-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
